export const SERVICETYPE = {
  CARE_BEAR_SERVICE: "CARE_BEAR_SERVICE",
};

export const MODAL_TYPES = {
  LINEAR_REGRESSION: "LINEAR REGRESSION",
  RANDOM_FOREST: "RANDOM FOREST",
  SUPPORT_VECTOR_MACHINE: "SVM",
  KMEAN_CLUSTERING: "K-MEAN",
};
